#!/usr/bin/env bash
#
# Thin sites: projects whose core is the gosite Go module, not copied code.
#
# A thin site is recognised by gosite.yml. Its files come in two kinds:
#
#   scaffold   written once by `gosite create` and owned by the site
#              from then on: main.go, site/, theme/, static/, go.mod,
#              cockpit/config.php and config.local.php, the override compose.
#   generated  rewritten by `gosite generate` from gosite.yml: the compose
#              files, the Dockerfiles and cockpit/config.core.php. Each carries
#              THIN_GENERATED_MARK, and a file that lost it is never overwritten.
#
# Requires lib/templates.sh (render_placeholders) and lib/siteyml.sh.

readonly THIN_GENERATED_MARK="generated by gosite generate"
readonly THIN_REPO="Avanxo-Technology/gosite-cli"

thin_template_root() { printf '%s' "${GOSITE_ROOT}/templates-thin"; }

# thin_is_project <dir>
thin_is_project() { [[ -f "$1/gosite.yml" ]]; }

# thin_core_version -> the core module version this CLI scaffolds against.
# CLI and core are released in lockstep (tags vX.Y.Z and core/vX.Y.Z).
thin_core_version() { printf '%s' "${GOSITE_VERSION}"; }

# thin_addon_library -> every addon gosite ships, one per line.
thin_addon_library() {
  local d
  for d in "${GOSITE_ROOT}/addons"/*/; do
    basename "${d}"
  done
}

# thin_disabled_addons <enabled...> -> a PHP array literal of the library
# addons not enabled. Webapp is never disabled: every site depends on it.
thin_disabled_addons() {
  local out="" name enabled keep
  while IFS= read -r name; do
    [[ "${name}" == "Webapp" ]] && continue
    keep=0
    for enabled in "$@"; do
      [[ "$(printf '%s' "${enabled}" | tr '[:upper:]' '[:lower:]')" == "$(printf '%s' "${name}" | tr '[:upper:]' '[:lower:]')" ]] && keep=1
    done
    [[ "${keep}" -eq 1 ]] && continue
    out+="${out:+, }'${name}'"
  done < <(thin_addon_library)
  printf '[%s]' "${out}"
}

# thin_write_siteyml <dir> <addons...> -> the initial gosite.yml.
thin_write_siteyml() {
  local dir="$1"; shift
  local flavor=plain
  [[ "${TAILWIND:-0}" -eq 1 ]] && flavor=tailwind
  cat > "${dir}/gosite.yml" <<EOF
# ${PROJECT_NAME} - declared once here, read by gosite and by the site itself.
# After editing, run 'gosite generate' and restart.

project: ${PROJECT_NAME}
module: ${PROJECT_MODULE}
core: $(thin_core_version)
flavor: ${flavor}
app_port: ${APP_PORT}
cms_port: ${CMS_PORT}
app_domain: ${APP_DOMAIN}
cms_domain: ${CMS_DOMAIN}
storage: ${STORAGE_ADAPTER:-s3}
database: ${DATABASE:-mongodb}
EOF
  siteyml_set_list "${dir}/gosite.yml" addons "$@"
}

# thin_load_render_vars <dir> -> the render variables from gosite.yml, plus the
# secrets create wrote to .env (so a regeneration never blanks them).
thin_load_render_vars() {
  local dir="$1" file="$1/gosite.yml"
  PROJECT_NAME="$(siteyml_get "${file}" project)"
  PROJECT_MODULE="$(siteyml_get "${file}" module)"
  APP_PORT="$(siteyml_get "${file}" app_port)"
  CMS_PORT="$(siteyml_get "${file}" cms_port)"
  APP_DOMAIN="$(siteyml_get "${file}" app_domain)"
  CMS_DOMAIN="$(siteyml_get "${file}" cms_domain)"
  STORAGE_ADAPTER="$(siteyml_get "${file}" storage)"
  DATABASE="$(siteyml_get "${file}" database)"
  # Flat commerce keys (design D4). commerce_region defaults to co so a site
  # that lists Commerce but has not set it still renders.
  COMMERCE_REGION="$(siteyml_get "${file}" commerce_region)"
  COMMERCE_REGION="${COMMERCE_REGION:-co}"
  THIN_CORE_VERSION="$(siteyml_get "${file}" core)"
  TAILWIND=0
  [[ "$(siteyml_get "${file}" flavor)" == "tailwind" ]] && TAILWIND=1
  INSTALL_ADDONS=0
  [[ -n "$(siteyml_list "${file}" addons)" ]] && INSTALL_ADDONS=1
  [[ -n "${PROJECT_NAME}" ]] || fatal "${file} has no 'project:'."
  CMS_TOKEN="$(_env_value "${dir}" COCKPIT_API_TOKEN)"
  COCKPIT_SEC_KEY="$(_env_value "${dir}" COCKPIT_SEC_KEY)"
  CMS_TOKEN="${CMS_TOKEN:-__CMS_TOKEN__}"
  COCKPIT_SEC_KEY="${COCKPIT_SEC_KEY:-__COCKPIT_SEC_KEY__}"
  export PROJECT_NAME PROJECT_MODULE APP_PORT CMS_PORT APP_DOMAIN CMS_DOMAIN \
         STORAGE_ADAPTER DATABASE TAILWIND INSTALL_ADDONS CMS_TOKEN COCKPIT_SEC_KEY \
         COMMERCE_REGION
}

# _thin_filter_addon_blocks <file> <addons...> -> keeps the body of every
# `# gosite:addon <Name>` ... `# gosite:end` block whose addon is listed and
# drops the rest, removing the marker lines either way. Blocks are never
# nested (design D3); matching is case-insensitive. This is how an addon can
# bring compose services: the block lives in the template, gosite.yml decides
# whether it survives rendering.
_thin_filter_addon_blocks() {
  local file="$1"; shift
  local enabled
  enabled=" $(printf '%s ' "$*" | tr '[:upper:]' '[:lower:]')"
  local tmp; tmp="$(mktemp)"
  THIN_ADDON_ENABLED="${enabled}" awk '
    BEGIN { enabled = ENVIRON["THIN_ADDON_ENABLED"] }
    /^[[:space:]]*# gosite:addon[[:space:]]/ {
      name = $0
      sub(/^[[:space:]]*# gosite:addon[[:space:]]*/, "", name)
      sub(/[[:space:]]+$/, "", name)
      keep = (index(enabled, " " tolower(name) " ") > 0)
      inblock = 1
      next
    }
    /^[[:space:]]*# gosite:end[[:space:]]*$/ { inblock = 0; keep = 1; next }
    { if (inblock && !keep) next; print }
  ' "${file}" > "${tmp}"
  mv "${tmp}" "${file}"
}

# _thin_render <file> <dir> -> thin-only placeholders, then the shared ones.
_thin_render() {
  local file="$1" dir="$2" tmp addons=() a
  while IFS= read -r a; do addons+=("${a}"); done < <(siteyml_list "${dir}/gosite.yml" addons)
  local version="${THIN_CORE_VERSION:-$(thin_core_version)}"
  tmp="$(mktemp)"
  sed \
    -e "s|__CORE_VERSION__|${version}|g" \
    -e "s|__ADDONS_CONTEXT_DEV__|${GOSITE_ROOT}/addons|g" \
    -e "s|__ADDONS_CONTEXT_REMOTE__|https://github.com/${THIN_REPO}.git#core/v${version}:src/addons|g" \
    -e "s|__DISABLED_ADDONS__|$(thin_disabled_addons "${addons[@]+"${addons[@]}"}")|g" \
    "${file}" > "${tmp}"
  mv "${tmp}" "${file}"
  # Drop addon blocks before the shared placeholders run, so a dropped block's
  # placeholders never reach assert_no_placeholders.
  _thin_filter_addon_blocks "${file}" "${addons[@]+"${addons[@]}"}"
  render_placeholders "${file}"
}

# thin_scaffold <dir> -> writes the site-owned files and the theme flavor.
thin_scaffold() {
  local dir="$1" root flavor=plain f rel
  root="$(thin_template_root)"
  [[ "${TAILWIND:-0}" -eq 1 ]] && flavor=tailwind
  while IFS= read -r -d '' f; do
    rel="${f#./}"
    _copy_template_file "${root}/scaffold" "${dir}" "${rel}"
    _thin_render "${dir}/$(_template_target_name "${rel}")" "${dir}"
  done < <(cd "${root}/scaffold" && find . -type f -print0)
  while IFS= read -r -d '' f; do
    rel="${f#./}"
    mkdir -p "$(dirname "${dir}/${rel}")"
    cp "${root}/flavors/${flavor}/${rel}" "${dir}/${rel}"
    _thin_render "${dir}/${rel}" "${dir}"
  done < <(cd "${root}/flavors/${flavor}" && find . -type f -print0)
}

# thin_ensure_commerce_secrets <dir> -> when Commerce is enabled, make sure the
# store's secrets exist in the project's .env. Values already present are never
# rewritten, so regenerating never rotates a live database password (design D9).
thin_ensure_commerce_secrets() {
  local dir="$1" envfile="$1/.env"
  siteyml_list "${dir}/gosite.yml" addons | grep -qix "Commerce" || return 0
  [[ -f "${envfile}" ]] || return 0

  _commerce_env_default "${envfile}" JWT_SECRET "$(random_secret 32)"
  _commerce_env_default "${envfile}" COOKIE_SECRET "$(random_secret 32)"
  _commerce_env_default "${envfile}" MEDUSA_DB_PASSWORD "$(random_secret 24)"
}

# _commerce_env_default <envfile> <key> <value> -> appends KEY=VALUE when the
# key is absent. An empty assignment counts as absent, so a blank value left by
# hand is filled in rather than kept.
_commerce_env_default() {
  local envfile="$1" key="$2" value="$3"
  local current
  current="$(_env_value "$(dirname "${envfile}")" "${key}")"
  [[ -n "${current}" ]] && return 0
  # Drop a blank line for the key so the appended value wins on dotenv reads.
  grep -qE "^${key}=$" "${envfile}" && { _delete_env_key "${envfile}" "${key}"; }
  printf '%s=%s\n' "${key}" "${value}" >> "${envfile}"
}

# _delete_env_key <envfile> <key> -> removes every line assigning that key.
_delete_env_key() {
  local envfile="$1" key="$2" tmp
  tmp="$(mktemp)"
  grep -vE "^${key}=" "${envfile}" > "${tmp}" || true
  mv "${tmp}" "${envfile}"
}

# thin_generate <dir> -> rewrites every generated file. Prints what it wrote,
# and names (without touching) any generated file that lost its mark; their
# count is left in THIN_SKIPPED.
thin_generate() {
  local dir="$1" root f rel tmpdir
  root="$(thin_template_root)"
  thin_is_project "${dir}" || fatal "$(basename "${dir}") has no gosite.yml: 'gosite generate' only manages thin sites. Upgrade other projects with MIGRATIONS.md."
  thin_load_render_vars "${dir}"
  thin_ensure_commerce_secrets "${dir}"

  THIN_SKIPPED=0
  tmpdir="$(mktemp -d)"
  while IFS= read -r -d '' f; do
    rel="${f#./}"
    # A file that lost its header was edited by hand: skipped, never
    # overwritten. cmd_generate reports those files.
    if [[ -f "${dir}/${rel}" ]] && ! head -n 3 "${dir}/${rel}" | grep -q "${THIN_GENERATED_MARK}"; then
      THIN_SKIPPED=$((THIN_SKIPPED + 1))
      continue
    fi
    mkdir -p "$(dirname "${tmpdir}/${rel}")"
    cp "${root}/generated/${rel}" "${tmpdir}/${rel}"
    _thin_render "${tmpdir}/${rel}" "${dir}"
    mkdir -p "$(dirname "${dir}/${rel}")"
    mv "${tmpdir}/${rel}" "${dir}/${rel}"
    printf '%s\n' "${rel}"
  done < <(cd "${root}/generated" && find . -type f -print0)
  rm -rf "${tmpdir}"
  assert_no_placeholders "${dir}"
}
