#!/usr/bin/env bash
#
# Local TLS and DNS support for *.<TLD> domains.
#
# Certificates are issued by mkcert, whose CA is trusted by the system, so
# https://<project>.test loads without browser warnings. DNS is expected to be
# a dnsmasq wildcard pointing *.<TLD> at 127.0.0.1.
#

project_domain()     { printf '%s.%s' "$1" "${GOSITE_TLD}"; }
project_cms_domain() { printf 'cms.%s.%s' "$1" "${GOSITE_TLD}"; }

# --- DNS ---------------------------------------------------------------------
# True when the resolver actually answers for an arbitrary name under the TLD,
# which is the only check that matters. A wildcard is required so new projects
# work without touching any config.
dns_resolves() {
  local probe="gosite-dns-probe.${GOSITE_TLD}"
  if command -v dscacheutil >/dev/null 2>&1; then
    dscacheutil -q host -a name "${probe}" 2>/dev/null | grep -q '^ip_address: 127\.0\.0\.1'
  elif command -v getent >/dev/null 2>&1; then
    getent hosts "${probe}" 2>/dev/null | grep -q '^127\.0\.0\.1'
  else
    return 1
  fi
}

dns_setup_hint() {
  cat <<EOF
Point *.${GOSITE_TLD} at 127.0.0.1 with dnsmasq:

    brew install dnsmasq
    echo 'address=/.${GOSITE_TLD}/127.0.0.1' >> $(brew --prefix 2>/dev/null || echo /usr/local)/etc/dnsmasq.conf
    sudo brew services restart dnsmasq
    sudo mkdir -p /etc/resolver
    echo 'nameserver 127.0.0.1' | sudo tee /etc/resolver/${GOSITE_TLD}

Verify with:  ping -c1 anything.${GOSITE_TLD}
EOF
}

# --- certificates ------------------------------------------------------------
mkcert_available() { command -v mkcert >/dev/null 2>&1; }

mkcert_ca_installed() {
  local root; root="$(mkcert -CAROOT 2>/dev/null)" || return 1
  [[ -n "${root}" && -f "${root}/rootCA.pem" ]]
}

# Issues one certificate per project covering <name>.<TLD> and *.<name>.<TLD>,
# which is what makes cms.<name>.<TLD> valid too. A wildcard only matches a
# single label, so a shared *.<TLD> certificate could not cover the CMS host.
ensure_project_cert() {
  local name="$1"
  local cert="${GOSITE_CERTS_DIR}/${name}.pem"
  local key="${GOSITE_CERTS_DIR}/${name}-key.pem"

  if [[ -f "${cert}" && -f "${key}" ]]; then
    write_cert_dynamic_config "${name}"
    return 0
  fi

  if ! mkcert_available; then
    warn "mkcert not found; HTTPS for $(project_domain "${name}") will not work."
    warn "Install it with: brew install mkcert && mkcert -install"
    return 1
  fi
  if ! mkcert_ca_installed; then
    warn "mkcert's local CA is not installed. Run: mkcert -install"
    return 1
  fi

  mkdir -p "${GOSITE_CERTS_DIR}"
  info "Issuing certificate for $(project_domain "${name}") and *.$(project_domain "${name}")"
  if ! mkcert -cert-file "${cert}" -key-file "${key}" \
        "$(project_domain "${name}")" "*.$(project_domain "${name}")" >/dev/null 2>&1; then
    warn "mkcert failed; continuing without HTTPS for this project."
    return 1
  fi
  chmod 0644 "${cert}" "${key}"

  write_cert_dynamic_config "${name}"
  ok "Certificate issued."
}

# Traefik picks certificates up from its watched dynamic directory, so adding a
# project never requires restarting the proxy.
write_cert_dynamic_config() {
  local name="$1"
  mkdir -p "${GOSITE_DYNAMIC_DIR}"
  cat > "${GOSITE_DYNAMIC_DIR}/${name}.yml" <<EOF
# Generated by gosite for ${name}. Do not edit.
tls:
  certificates:
    - certFile: /certs/${name}.pem
      keyFile: /certs/${name}-key.pem
EOF
}

remove_project_cert() {
  local name="$1"
  rm -f "${GOSITE_CERTS_DIR}/${name}.pem" \
        "${GOSITE_CERTS_DIR}/${name}-key.pem" \
        "${GOSITE_DYNAMIC_DIR}/${name}.yml"
}
