#!/usr/bin/env bats
# gosite.yml read/write from bash (src/lib/siteyml.sh). Core's Go parser reads
# the same subset; these cases mirror core/internal/siteconfig's tests.

setup() {
  load helpers
  _env_reset
  # shellcheck source=../src/lib/siteyml.sh
  source "${BATS_TEST_DIRNAME}/../src/lib/siteyml.sh"
  F="${GOSITE_TEST_ROOT}/gosite-${RANDOM}.yml"
  cat > "${F}" <<'EOF'
# generated by gosite create
project: demo
core: "0.54.0"   # the core module version
storage: s3

addons:
  - Blog
  - 'Forms'
flavor: tailwind
EOF
}

@test "get reads a scalar, unquoted and without a trailing comment" {
  [ "$(siteyml_get "${F}" project)" = "demo" ]
  [ "$(siteyml_get "${F}" core)" = "0.54.0" ]
  [ "$(siteyml_get "${F}" flavor)" = "tailwind" ]
  [ -z "$(siteyml_get "${F}" missing)" ]
}

@test "list reads the items under a key" {
  run siteyml_list "${F}" addons
  [ "${status}" -eq 0 ]
  [ "${output}" = $'Blog\nForms' ]
}

@test "set_list replaces the list and keeps every other line" {
  siteyml_set_list "${F}" addons Blog Analytics
  [ "$(siteyml_list "${F}" addons)" = $'Blog\nAnalytics' ]
  [ "$(siteyml_get "${F}" flavor)" = "tailwind" ]
  [ "$(siteyml_get "${F}" storage)" = "s3" ]
  grep -q '^# generated by gosite create' "${F}"
}

@test "set_list with no items writes an empty list" {
  siteyml_set_list "${F}" addons
  grep -q '^addons: \[\]$' "${F}"
  [ -z "$(siteyml_list "${F}" addons)" ]
  [ "$(siteyml_get "${F}" flavor)" = "tailwind" ]
}

@test "set_list appends a list the file does not have yet" {
  siteyml_set_list "${F}" extras one
  [ "$(siteyml_list "${F}" extras)" = "one" ]
  [ "$(siteyml_list "${F}" addons)" = $'Blog\nForms' ]
}
