#!/usr/bin/env bash
#
# gosite infra <up|down|status|logs>
#
# Manages the shared infrastructure (Traefik + Redis) that every project on
# the machine attaches to through the external '${GOSITE_NETWORK}' network.
#

# Traefik's static configuration. The docker provider discovers project
# containers by label; the file provider watches the directory where gosite
# drops one TLS block per project, so new sites need no proxy restart.
_infra_write_traefik_config() {
  mkdir -p "${GOSITE_INFRA_DIR}/traefik" "${GOSITE_DYNAMIC_DIR}" "${GOSITE_CERTS_DIR}"
  cat > "${GOSITE_INFRA_DIR}/traefik/traefik.yml" <<EOF
# Generated by gosite. Do not edit.
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: false
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: ${GOSITE_NETWORK}
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true
  insecure: false

log:
  level: INFO

accessLog: {}
EOF
}

_infra_write_compose() {
  mkdir -p "${GOSITE_INFRA_DIR}"
  cat > "${GOSITE_INFRA_DIR}/docker-compose.yml" <<EOF
# Generated by gosite. Shared local infrastructure for every project.
services:
  proxy:
    image: traefik:${GOSITE_TRAEFIK_VERSION}
    container_name: ${GOSITE_PROXY_HOST}
    restart: unless-stopped
    environment:
      # Docker Engine 29 dropped the legacy API versions Traefik negotiates by
      # default, which makes the docker provider fail with an empty daemon
      # error. Pinning the API version keeps discovery working.
      DOCKER_API_VERSION: "1.44"
    ports:
      - "${GOSITE_PROXY_HTTP_PORT}:80"
      - "${GOSITE_PROXY_HTTPS_PORT}:443"
    volumes:
      # Read-only socket: Traefik only needs to watch container labels.
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${GOSITE_DYNAMIC_DIR}:/etc/traefik/dynamic:ro
      - ${GOSITE_CERTS_DIR}:/certs:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.gosite-dashboard.rule=Host(\`proxy.${GOSITE_TLD}\`)
      - traefik.http.routers.gosite-dashboard.entrypoints=websecure
      - traefik.http.routers.gosite-dashboard.tls=true
      - traefik.http.routers.gosite-dashboard.service=api@internal
    networks: [gosite]

  redis:
    image: redis:${GOSITE_REDIS_VERSION}-alpine
    container_name: ${GOSITE_REDIS_HOST}
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "${GOSITE_REDIS_PORT}:6379"
    volumes:
      - gosite-redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [gosite]

  mongo:
    image: mongo:${GOSITE_MONGO_VERSION}
    container_name: ${GOSITE_MONGO_HOST}
    restart: unless-stopped
    ports:
      - "${GOSITE_MONGO_PORT}:27017"
    volumes:
      - gosite-mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks: [gosite]

volumes:
  gosite-redisdata:
  gosite-mongodata:

networks:
  gosite:
    external: true
    name: ${GOSITE_NETWORK}
EOF
}

_infra_compose() {
  compose -p "${GOSITE_INFRA_PROJECT}" -f "${GOSITE_INFRA_DIR}/docker-compose.yml" "$@"
}

cmd_infra() {
  local action="${1:-status}"
  [[ $# -gt 0 ]] && shift || true
  require_dependencies

  case "${action}" in
    up)
      ensure_network
      _infra_write_traefik_config
      _infra_write_compose

      # The dashboard is served over HTTPS like everything else.
      ensure_project_cert "proxy" >/dev/null 2>&1 || true

      info "Starting shared infrastructure (proxy, ${GOSITE_REDIS_HOST}, ${GOSITE_MONGO_HOST})"
      _infra_compose up -d
      ok "Proxy     -> https://proxy.${GOSITE_TLD} (Traefik dashboard)"
      ok "Redis     -> localhost:${GOSITE_REDIS_PORT}"
      ok "MongoDB   -> localhost:${GOSITE_MONGO_PORT}"
      printf "${C_DIM}From a project container reach them by the hostnames '%s' and '%s'.${C_NC}\n" \
        "${GOSITE_REDIS_HOST}" "${GOSITE_MONGO_HOST}"

      dns_resolves || {
        warn "*.${GOSITE_TLD} does not resolve to 127.0.0.1, so local domains will not work."
        dns_setup_hint
      }
      ;;
    down)
      [[ -f "${GOSITE_INFRA_DIR}/docker-compose.yml" ]] || fatal "Infrastructure was never created. Run 'gosite infra up'."
      info "Stopping shared infrastructure"
      _infra_compose down
      ok "Infrastructure stopped (data volumes preserved)."
      ;;
    restart)
      [[ -f "${GOSITE_INFRA_DIR}/docker-compose.yml" ]] || fatal "Infrastructure was never created. Run 'gosite infra up'."
      info "Restarting shared infrastructure"
      _infra_compose restart "$@"
      ok "Infrastructure restarted."
      ;;
    status)
      if network_exists "${GOSITE_NETWORK}"; then
        ok "Network '${GOSITE_NETWORK}' exists."
      else
        warn "Network '${GOSITE_NETWORK}' is missing. Run 'gosite infra up'."
      fi
      if dns_resolves; then
        ok "*.${GOSITE_TLD} resolves to 127.0.0.1."
      else
        err "*.${GOSITE_TLD} does not resolve. Local domains will not work."
        dns_setup_hint
      fi

      if ! mkcert_available; then
        warn "mkcert not installed; HTTPS certificates cannot be issued (brew install mkcert)."
      elif ! mkcert_ca_installed; then
        warn "mkcert CA not installed. Run: mkcert -install"
      else
        ok "mkcert CA is installed."
      fi

      local svc
      for svc in "${GOSITE_PROXY_HOST}" "${GOSITE_REDIS_HOST}" "${GOSITE_MONGO_HOST}"; do
        if container_running "${svc}"; then
          ok "${svc}: running"
        elif container_exists "${svc}"; then
          warn "${svc}: stopped"
        else
          err "${svc}: not created"
        fi
      done
      ;;
    logs)
      [[ -f "${GOSITE_INFRA_DIR}/docker-compose.yml" ]] || fatal "Infrastructure was never created."
      _infra_compose logs -f --tail=100 "$@"
      ;;
    *)
      fatal "Unknown 'infra' action: ${action} (expected up|down|status|logs)"
      ;;
  esac
}
