#!/usr/bin/env bash
#
# gosite infra <up|down|status|logs>
#
# Manages the shared infrastructure (Traefik + Redis) that every project on
# the machine attaches to through the external '${GOSITE_NETWORK}' network.
#

# Traefik's static configuration. The docker provider discovers project
# containers by label; the file provider watches the directory where gosite
# drops one TLS block per project, so new sites need no proxy restart.
_infra_write_traefik_config() {
  mkdir -p "${GOSITE_INFRA_DIR}/traefik" "${GOSITE_DYNAMIC_DIR}" "${GOSITE_CERTS_DIR}"
  cat > "${GOSITE_INFRA_DIR}/traefik/traefik.yml" <<EOF
# Generated by gosite. Do not edit.
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: false
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: ${GOSITE_NETWORK}
  file:
    directory: /etc/traefik/dynamic
    watch: true

serversTransport:
  insecureSkipVerify: true

api:
  dashboard: true
  insecure: false

log:
  level: INFO

accessLog: {}
EOF
}

_infra_write_compose() {
  mkdir -p "${GOSITE_INFRA_DIR}"
  cat > "${GOSITE_INFRA_DIR}/docker-compose.yml" <<EOF
# Generated by gosite. Shared local infrastructure for every project.
services:
  proxy:
    image: traefik:${GOSITE_TRAEFIK_VERSION}
    container_name: ${GOSITE_PROXY_HOST}
    restart: unless-stopped
    environment:
      # Docker Engine 29 dropped the legacy API versions Traefik negotiates by
      # default, which makes the docker provider fail with an empty daemon
      # error. Pinning the API version keeps discovery working.
      DOCKER_API_VERSION: "1.44"
    ports:
      - "${GOSITE_PROXY_HTTP_PORT}:80"
      - "${GOSITE_PROXY_HTTPS_PORT}:443"
    volumes:
      # Read-only socket: Traefik only needs to watch container labels.
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${GOSITE_DYNAMIC_DIR}:/etc/traefik/dynamic:ro
      - ${GOSITE_CERTS_DIR}:/certs:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.gosite-dashboard.rule=Host(\`proxy.${GOSITE_TLD}\`)
      - traefik.http.routers.gosite-dashboard.entrypoints=websecure
      - traefik.http.routers.gosite-dashboard.tls=true
      - traefik.http.routers.gosite-dashboard.service=api@internal
    networks: [gosite]

  redis:
    image: redis:${GOSITE_REDIS_VERSION}-alpine
    container_name: ${GOSITE_REDIS_HOST}
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "allkeys-lru"]
    ports:
      # Loopback only (see GOSITE_BIND_ADDRESS): this Redis runs without auth.
      - "${GOSITE_BIND_ADDRESS}:${GOSITE_REDIS_PORT}:6379"
    volumes:
      - gosite-redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [gosite]

  mongo:
    image: mongo:${GOSITE_MONGO_VERSION}
    container_name: ${GOSITE_MONGO_HOST}
    restart: unless-stopped
    ports:
      # Loopback only: the shared dev Mongo runs without authentication.
      - "${GOSITE_BIND_ADDRESS}:${GOSITE_MONGO_PORT}:27017"
    volumes:
      - gosite-mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks: [gosite]

  minio:
    image: minio/minio:latest
    container_name: ${GOSITE_MINIO_HOST}
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # Public URLs for reverse-proxy mode so the console links back to the
      # right host (S3 API behind minio.<TLD>, console behind minio-console.<TLD>).
      MINIO_SERVER_URL: "https://minio.${GOSITE_TLD}"
      MINIO_BROWSER_REDIRECT_URL: "https://minio-console.${GOSITE_TLD}"
    ports:
      # Plain-HTTP fallbacks; HTTPS is served natively by MinIO and through
      # Traefik below. Loopback only (see GOSITE_BIND_ADDRESS).
      - "${GOSITE_BIND_ADDRESS}:9002:9000"
      - "${GOSITE_BIND_ADDRESS}:9003:9001"
    volumes:
      # Native TLS: the mkcert cert generated by ensure_minio_certs is mounted
      # as MinIO's own cert, so container-to-container S3 traffic (CMS) is
      # HTTPS too. The same cert covers the Traefik hostnames.
      - ${GOSITE_CERTS_DIR}/minio.pem:/root/.minio/certs/public.crt:ro
      - ${GOSITE_CERTS_DIR}/minio-key.pem:/root/.minio/certs/private.key:ro
      - gosite-miniodata:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=gosite-network
      # Backend is HTTPS (native MinIO TLS); skip cert verification since the
      # proxy trusts no CA, the mkcert cert is only in the CMS/browser trust.
      - traefik.http.services.gosite-minio-s3.loadbalancer.server.port=9000
      - traefik.http.services.gosite-minio-s3.loadbalancer.server.scheme=https
      - traefik.http.services.gosite-minio-s3.loadbalancer.serverstransport=default@internal
      - traefik.http.routers.gosite-minio-s3.rule=Host(\`minio.${GOSITE_TLD}\`)
      - traefik.http.routers.gosite-minio-s3.entrypoints=websecure
      - traefik.http.routers.gosite-minio-s3.tls=true
      - traefik.http.routers.gosite-minio-s3.service=gosite-minio-s3
      - traefik.http.services.gosite-minio-console.loadbalancer.server.port=9001
      - traefik.http.services.gosite-minio-console.loadbalancer.server.scheme=https
      - traefik.http.services.gosite-minio-console.loadbalancer.serverstransport=default@internal
      - traefik.http.routers.gosite-minio-console.rule=Host(\`minio-console.${GOSITE_TLD}\`)
      - traefik.http.routers.gosite-minio-console.entrypoints=websecure
      - traefik.http.routers.gosite-minio-console.tls=true
      - traefik.http.routers.gosite-minio-console.service=gosite-minio-console
    healthcheck:
      # -k because the probe talks to MinIO's own mkcert certificate.
      test: ["CMD", "curl", "-fk", "https://127.0.0.1:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [gosite]

volumes:
  gosite-redisdata:
  gosite-mongodata:
  gosite-miniodata:

networks:
  gosite:
    external: true
    name: ${GOSITE_NETWORK}
EOF
}

# Resolves the shared MinIO root credentials for this installation and warns
# when a legacy minioadmin installation is detected. The resolution itself
# (reuse stored file / legacy detection / fresh generation) lives in
# resolve_minio_credentials (helpers.sh) so `create` and `sync` propagate the
# same credentials into project .env files.
_infra_minio_credentials() {
  GOSITE_MINIO_LEGACY=0
  resolve_minio_credentials

  if [[ "${GOSITE_MINIO_LEGACY:-0}" -eq 1 ]]; then
    local credfile="${GOSITE_INFRA_DIR}/minio.env"
    warn "MinIO still uses the fixed minioadmin/minioadmin credentials from before gosite generated them;"
    warn "kept as-is so your existing bucket data stays reachable. Rotate them with:"
    warn "  1. gosite infra down"
    warn "  2. rm ${credfile} 2>/dev/null; docker volume rm $(docker volume ls --format '{{.Name}}' 2>/dev/null | grep 'gosite-miniodata' | head -1)   # only if the bucket can be emptied"
    warn "  3. gosite infra up          # generates fresh random credentials"
    warn "     (to keep objects: create a new bucket under the new credentials and copy data over with 'mc mirror')"
    warn "Then update S3_KEY / S3_SECRET in each project's .env by hand."
  fi
}

_infra_compose() {
  compose -p "${GOSITE_INFRA_PROJECT}" -f "${GOSITE_INFRA_DIR}/docker-compose.yml" "$@"
}

# Issues a single mkcert certificate covering everything MinIO needs: the
# container hostname (used internally by the CMS over HTTPS), the Traefik
# hostnames minio.<TLD> / minio-console.<TLD> and localhost. The same files are
# mounted into the MinIO container as its native TLS cert and registered with
# Traefik for both public hostnames.
ensure_minio_certs() {
  local cert="${GOSITE_CERTS_DIR}/minio.pem"
  local key="${GOSITE_CERTS_DIR}/minio-key.pem"

  if [[ -f "${cert}" && -f "${key}" ]]; then
    write_cert_dynamic_config "minio"
    return 0
  fi

  if ! mkcert_available || ! mkcert_ca_installed; then
    warn "mkcert missing or its CA is not installed; MinIO will run without native TLS."
    return 1
  fi

  mkdir -p "${GOSITE_CERTS_DIR}"
  info "Issuing MinIO certificate (gosite-minio, minio.${GOSITE_TLD}, minio-console.${GOSITE_TLD}, localhost)"
  if ! mkcert -cert-file "${cert}" -key-file "${key}" \
        "${GOSITE_MINIO_HOST}" "localhost" "127.0.0.1" \
        "minio.${GOSITE_TLD}" "minio-console.${GOSITE_TLD}" \
        "*.minio.${GOSITE_TLD}" "*.minio-console.${GOSITE_TLD}" >/dev/null 2>&1; then
    warn "mkcert failed; MinIO will run without native TLS."
    return 1
  fi
  chmod 0644 "${cert}" "${key}"

  write_cert_dynamic_config "minio"
  ok "MinIO certificate issued."
}

cmd_infra() {
  local action="${1:-status}"
  [[ $# -gt 0 ]] && shift || true
  require_dependencies

  case "${action}" in
    up)
      ensure_network
      _infra_write_traefik_config

      # Credentials must be resolved before the compose file is written: the
      # MinIO service reads them from the environment.
      _infra_minio_credentials
      _infra_write_compose

      # Deliberate LAN exposure deserves a loud warning: these services have no
      # (or fixed) authentication.
      if [[ "${GOSITE_BIND_ADDRESS}" == "0.0.0.0" ]]; then
        warn "GOSITE_BIND_ADDRESS=0.0.0.0 publishes datastores on every interface:"
        warn "  ${GOSITE_REDIS_HOST} (no auth), ${GOSITE_MONGO_HOST} (no auth), ${GOSITE_MINIO_HOST} (MinIO)."
        warn "Anyone on your network can read and write them. Use a loopback bind unless you truly need LAN access."
      fi

      # Self-heal a proxy that lost its network: if gosite-network was removed
      # and recreated while the proxy kept running, docker compose sees no
      # config change and never reattaches it - then Traefik cannot see any
      # project container. Reattach here, non-destructively.
      if container_exists "${GOSITE_PROXY_HOST}" \
          && ! container_on_network "${GOSITE_PROXY_HOST}" "${GOSITE_NETWORK}"; then
        warn "Proxy is not attached to '${GOSITE_NETWORK}'; reattaching so it can route projects."
        docker network connect "${GOSITE_NETWORK}" "${GOSITE_PROXY_HOST}" >/dev/null 2>&1 \
          || info "Reattach failed; 'gosite infra restart' will recreate the proxy."
      fi

      # The dashboard is served over HTTPS like everything else.
      ensure_project_cert "proxy" >/dev/null 2>&1 || true
      # MinIO: one combined mkcert certificate for the container hostname (used
      # internally by the CMS), the Traefik hostnames and localhost. It is both
      # MinIO's native TLS cert and the one Traefik serves for minio.<TLD>.
      ensure_minio_certs || true

      info "Starting shared infrastructure (proxy, ${GOSITE_REDIS_HOST}, ${GOSITE_MONGO_HOST}, ${GOSITE_MINIO_HOST})"
      _infra_compose up -d

      # --- self-heal stale labels -------------------------------------------------
      # `docker compose up -d` does not recreate containers when only labels
      # change, so after an update the proxy/minio containers can keep the old
      # (broken) Traefik labels. Detect this and force-recreate when needed.
      local stale=0
      if container_running "${GOSITE_PROXY_HOST}"; then
        if ! container_label_matches "${GOSITE_PROXY_HOST}" \
            "traefik.http.routers.gosite-dashboard.rule" "Host(\`proxy.${GOSITE_TLD}\`)"; then
          stale=1
        fi
      fi
      if container_running "${GOSITE_MINIO_HOST}"; then
        if ! container_label_matches "${GOSITE_MINIO_HOST}" \
            "traefik.http.services.gosite-minio-s3.loadbalancer.serverstransport" "default@internal"; then
          stale=1
        fi
      fi
      if [[ "${stale}" -eq 1 ]]; then
        warn "Detected stale Traefik labels; force-recreating proxy and MinIO..."
        _infra_compose up -d --force-recreate proxy minio
      fi

      # Clean up stale dynamic config that older gosite versions generated.
      rm -f "${GOSITE_DYNAMIC_DIR}/minio-console.yml"

      # Create the default bucket in MinIO so projects can use it immediately.
      # -k/--insecure because MinIO serves its mkcert certificate.
      docker run --rm --network ${GOSITE_NETWORK} \
        --entrypoint sh minio/mc:latest \
        -c "mc alias set local https://${GOSITE_MINIO_HOST}:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} --insecure \
            && mc mb -p local/assets \
            && mc anonymous set download local/assets" \
        >/dev/null 2>&1 || true

      ok "Proxy     -> https://proxy.${GOSITE_TLD} (Traefik dashboard)"
      ok "Redis     -> ${GOSITE_BIND_ADDRESS}:${GOSITE_REDIS_PORT}"
      ok "MongoDB   -> ${GOSITE_BIND_ADDRESS}:${GOSITE_MONGO_PORT}"
      ok "MinIO     -> https://minio.${GOSITE_TLD} (S3 API) / https://minio-console.${GOSITE_TLD} (console)"
      printf "${C_DIM}Datastores publish on %s (override with GOSITE_BIND_ADDRESS); project containers reach them by hostname.${C_NC}\n" "${GOSITE_BIND_ADDRESS}"
      printf "${C_DIM}From a project container reach them by the hostnames '%s', '%s' and '%s'.${C_NC}\n" \
        "${GOSITE_REDIS_HOST}" "${GOSITE_MONGO_HOST}" "${GOSITE_MINIO_HOST}"

      dns_resolves || {
        warn "*.${GOSITE_TLD} does not resolve to 127.0.0.1, so local domains will not work."
        dns_setup_hint
      }
      ;;
    down)
      [[ -f "${GOSITE_INFRA_DIR}/docker-compose.yml" ]] || fatal "Infrastructure was never created. Run 'gosite infra up'."
      info "Stopping shared infrastructure"
      _infra_compose down
      ok "Infrastructure stopped (data volumes preserved)."
      ;;
    restart)
      [[ -f "${GOSITE_INFRA_DIR}/docker-compose.yml" ]] || fatal "Infrastructure was never created. Run 'gosite infra up'."
      info "Restarting shared infrastructure"
      _infra_compose restart "$@"
      ok "Infrastructure restarted."
      ;;
    status)
      if network_exists "${GOSITE_NETWORK}"; then
        ok "Network '${GOSITE_NETWORK}' exists."
      else
        warn "Network '${GOSITE_NETWORK}' is missing. Run 'gosite infra up'."
      fi
      if dns_resolves; then
        ok "*.${GOSITE_TLD} resolves to 127.0.0.1."
      else
        err "*.${GOSITE_TLD} does not resolve. Local domains will not work."
        dns_setup_hint
      fi

      if ! mkcert_available; then
        warn "mkcert not installed; HTTPS certificates cannot be issued (brew install mkcert)."
      elif ! mkcert_ca_installed; then
        warn "mkcert CA not installed. Run: mkcert -install"
      else
        ok "mkcert CA is installed."
      fi

      local svc
      for svc in "${GOSITE_PROXY_HOST}" "${GOSITE_REDIS_HOST}" "${GOSITE_MONGO_HOST}" "gosite-minio"; do
        if container_running "${svc}"; then
          ok "${svc}: running"
        elif container_exists "${svc}"; then
          warn "${svc}: stopped"
        else
          err "${svc}: not created"
        fi
      done
      ;;
    logs)
      [[ -f "${GOSITE_INFRA_DIR}/docker-compose.yml" ]] || fatal "Infrastructure was never created."
      _infra_compose logs -f --tail=100 "$@"
      ;;
    repair)
      [[ -f "${GOSITE_INFRA_DIR}/docker-compose.yml" ]] || fatal "Infrastructure was never created. Run 'gosite infra up'."
      info "Regenerating Traefik and compose configs..."
      _infra_write_traefik_config
      _infra_minio_credentials
      _infra_write_compose
      ensure_minio_certs || true

      info "Recreating all services with new config..."
      _infra_compose up -d --force-recreate

      # Ensure the assets bucket exists and has a public-read policy.
      docker run --rm --network ${GOSITE_NETWORK} \
        --entrypoint sh minio/mc:latest \
        -c "mc alias set local https://${GOSITE_MINIO_HOST}:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} --insecure \
            && mc mb -p local/assets \
            && mc anonymous set download local/assets" \
        >/dev/null 2>&1 || true

      ok "Infrastructure configs repaired and services recreated."
      ;;
    *)
      fatal "Unknown 'infra' action: ${action} (expected up|down|restart|status|logs|repair)"
      ;;
  esac
}
