package siteconfig

import (
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

func TestParse(t *testing.T) {
	c, err := Parse(strings.NewReader(`# generated by gosite create
project: demo
core: "0.54.0"   # the core module version
storage: s3

addons:
  - Blog
  - 'Forms'
flavor: tailwind
`))
	if err != nil {
		t.Fatal(err)
	}
	if c.Values["project"] != "demo" || c.Values["core"] != "0.54.0" || c.Values["flavor"] != "tailwind" {
		t.Errorf("values = %v", c.Values)
	}
	if !slices.Equal(c.Addons(), []string{"Blog", "Forms"}) {
		t.Errorf("addons = %v", c.Addons())
	}
}

func TestEmptyList(t *testing.T) {
	for _, src := range []string{"addons: []\n", "addons:\n"} {
		c, err := Parse(strings.NewReader(src))
		if err != nil {
			t.Fatal(err)
		}
		if len(c.Addons()) != 0 {
			t.Errorf("%q: addons = %v", src, c.Addons())
		}
	}
}

func TestRejectsWhatBashCannotRead(t *testing.T) {
	for _, src := range []string{"db:\n  host: x\n", "- orphan\n", "just text\n"} {
		if _, err := Parse(strings.NewReader(src)); err == nil {
			t.Errorf("%q parsed without error", src)
		}
	}
}

func TestMissingFileIsEmpty(t *testing.T) {
	c, err := Load(filepath.Join(t.TempDir(), File))
	if err != nil || len(c.Addons()) != 0 {
		t.Fatalf("Load(missing) = %v, %v", c, err)
	}
}
